"""initial schema

Revision ID: c6a213b53ed1
Revises: 
Create Date: 2026-09-30 20:18:35.129027

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c6a213b53ed1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'UPLOADED', 'PROCESSING', 'READY', 'PARTIAL', 'FAILED', 'DELETING', name='room_status'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('owner_participant_id', sa.UUID(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_participant_id'], ['participants.id'], name='fk_rooms_owner_participant_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='fk_rooms_video_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rooms_deleted_at', 'rooms', ['deleted_at'], unique=False)
    op.create_index('ix_rooms_status_expires', 'rooms', ['status', 'expires_at'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(display_name) between 1 and 40', name='ck_participants_name_len'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'display_name', name='uq_participants_room_name')
    )
    op.create_index('ix_participants_room', 'participants', ['room_id'], unique=False)
    op.create_table('render_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'MIXING', 'ENCODING', 'DONE', 'FAILED', 'CANCELED', name='render_status'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('options_hash', sa.String(length=64), nullable=False),
    sa.Column('lines_version', sa.Integer(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('recorded_lines', sa.Integer(), nullable=False),
    sa.Column('used_lines', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.Text(), nullable=True),
    sa.Column('audio_mix_path', sa.Text(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'options_hash', 'lines_version', name='uq_render_idempotency')
    )
    op.create_index('ix_render_jobs_room_created', 'render_jobs', ['room_id', 'created_at'], unique=False)
    op.create_index('uq_render_current_per_room', 'render_jobs', ['room_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('room_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_events_room_id', 'room_events', ['room_id', 'id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(length=20), nullable=False),
    sa.Column('storage_dir', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('container', sa.String(length=32), nullable=False),
    sa.Column('video_codec', sa.String(length=32), nullable=True),
    sa.Column('audio_codec', sa.String(length=32), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('probe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_ms between 1 and 3600000', name='ck_videos_duration'),
    sa.CheckConstraint('size_bytes > 0', name='ck_videos_size_pos'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_room', 'videos', ['room_id'], unique=False)
    op.create_index('ix_videos_sha', 'videos', ['sha256'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(length=20), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'FAILED', 'CANCELED', 'DONE', name='job_status'), nullable=False),
    sa.Column('current_stage', sa.Enum('EXTRACT_AUDIO', 'SEPARATE_SPEECH', 'TRANSCRIBE', 'DIARIZE', 'MERGE_DIALOGUE', name='stage_name'), nullable=True),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress between 0 and 100', name='ck_jobs_progress'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', name='uq_processing_jobs_video')
    )
    op.create_index('ix_processing_jobs_room_status', 'processing_jobs', ['room_id', 'status'], unique=False)
    op.create_table('dialogue_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('speaker_key', sa.String(length=32), nullable=False),
    sa.Column('speaker_label', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('overlaps', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('keep_original', sa.Boolean(), nullable=False),
    sa.Column('speech_path', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_ms - start_ms between 100 and 60000', name='ck_lines_duration_range'),
    sa.CheckConstraint('end_ms > start_ms', name='ck_lines_end_gt_start'),
    sa.CheckConstraint('start_ms >= 0', name='ck_lines_start_nonneg'),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lines_room_idx', 'dialogue_lines', ['room_id', 'idx'], unique=True)
    op.create_index('ix_lines_room_speaker', 'dialogue_lines', ['room_id', 'speaker_key'], unique=False)
    op.create_index('ix_lines_room_start', 'dialogue_lines', ['room_id', 'start_ms'], unique=False)
    op.create_table('job_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('EXTRACT_AUDIO', 'SEPARATE_SPEECH', 'TRANSCRIBE', 'DIARIZE', 'MERGE_DIALOGUE', name='stage_name'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'SKIPPED', 'FAILED', 'CANCELED', name='stage_status'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress between 0 and 100', name='ck_stages_progress'),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'stage', 'attempt', name='uq_job_stages_attempt')
    )
    op.create_index('ix_job_stages_job', 'job_stages', ['job_id'], unique=False)
    op.create_table('assignments',
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['dialogue_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index('ix_assignments_expires', 'assignments', ['expires_at'], unique=False)
    op.create_index('ix_assignments_participant', 'assignments', ['participant_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('take_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'REJECTED', 'FAILED', name='recording_status'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('raw_path', sa.Text(), nullable=False),
    sa.Column('processed_path', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('loudness_lufs', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('line_version_at_record', sa.Integer(), nullable=True),
    sa.Column('rejected_reason', sa.String(length=64), nullable=True),
    sa.Column('orphaned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name='ck_recordings_size_pos'),
    sa.CheckConstraint('take_number > 0', name='ck_recordings_take_pos'),
    sa.ForeignKeyConstraint(['line_id'], ['dialogue_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'take_number', name='uq_recordings_line_take')
    )
    op.create_index('ix_recordings_participant', 'recordings', ['participant_id'], unique=False)
    op.create_index('uq_recordings_current_per_line', 'recordings', ['line_id'], unique=True, postgresql_where=sa.text('is_current'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_recordings_current_per_line', table_name='recordings', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_recordings_participant', table_name='recordings')
    op.drop_table('recordings')
    op.drop_index('ix_assignments_participant', table_name='assignments')
    op.drop_index('ix_assignments_expires', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_job_stages_job', table_name='job_stages')
    op.drop_table('job_stages')
    op.drop_index('ix_lines_room_start', table_name='dialogue_lines')
    op.drop_index('ix_lines_room_speaker', table_name='dialogue_lines')
    op.drop_index('ix_lines_room_idx', table_name='dialogue_lines')
    op.drop_table('dialogue_lines')
    op.drop_index('ix_processing_jobs_room_status', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_videos_sha', table_name='videos')
    op.drop_index('ix_videos_room', table_name='videos')
    op.drop_table('videos')
    op.drop_index('ix_room_events_room_id', table_name='room_events')
    op.drop_table('room_events')
    op.drop_index('uq_render_current_per_room', table_name='render_jobs', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_render_jobs_room_created', table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_index('ix_participants_room', table_name='participants')
    op.drop_table('participants')
    op.drop_index('ix_rooms_status_expires', table_name='rooms')
    op.drop_index('ix_rooms_deleted_at', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
